<a href="https://colab.research.google.com/github/3B032049/2025_ML_hws/blob/main/hw6-4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np


x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, -1])
x3 = np.array([-2, 0, 2])



# 整合為一個矩陣 X（3 個詞，維度為 3）
X = np.stack([x1, x2, x3])  # shape: (3, 3)

Wq = np.array([[0, 0 ,1],
        [1, 0 ,0],
        [0, 0 ,1]])

Wk = np.array([[1, 0 ,1],
        [0, 1 ,1],
        [0, 1 ,0]])

Wv = np.array([[0, 2 ,1],
        [1, 0 ,3],
        [1, 0 ,1]])

b = np.array([0.01, 0.02, 0.03, 0.04])  # shape: (4,)



In [10]:
Q = X @ Wq
K = X @ Wk
V = X @ Wv

print("Q \n", Q)
print("K \n", K)
print("V \n", V)

Q 
 [[ 2  0  4]
 [ 1  0 -1]
 [ 0  0  0]]
K 
 [[ 1  5  3]
 [ 0  0  1]
 [-2  2 -2]]
V 
 [[ 5  2 10]
 [ 0  0  2]
 [ 2 -4  0]]


In [11]:
def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / np.sum(e, axis=-1, keepdims=True)

In [12]:
dk = Q.shape[1]  # d_k = 2
scores = np.dot(Q , K.T) / np.sqrt(dk)  # shape: (3, 3)
weights = softmax(scores)       # shape: (3, 3)
attention_output = weights @ V  # shape: (3, 2)

print("注意力權重（softmax(QK^T/√dk)） =\n", weights)
print("Self-Attention Output =\n", attention_output)

print("注意力權重（softmax(QK^T/√dk)） =\n", weights)
print("Self-Attention Output =\n", attention_output)

注意力權重（softmax(QK^T/√dk)） =
 [[9.96900485e-01 3.09921316e-03 3.01585787e-07]
 [1.67943450e-01 2.99159712e-01 5.32896838e-01]
 [3.33333333e-01 3.33333333e-01 3.33333333e-01]]
Self-Attention Output =
 [[ 4.98450303  1.99379976  9.97520328]
 [ 1.90551093 -1.79570045  2.27775393]
 [ 2.33333333 -0.66666667  4.        ]]
注意力權重（softmax(QK^T/√dk)） =
 [[9.96900485e-01 3.09921316e-03 3.01585787e-07]
 [1.67943450e-01 2.99159712e-01 5.32896838e-01]
 [3.33333333e-01 3.33333333e-01 3.33333333e-01]]
Self-Attention Output =
 [[ 4.98450303  1.99379976  9.97520328]
 [ 1.90551093 -1.79570045  2.27775393]
 [ 2.33333333 -0.66666667  4.        ]]


In [13]:
#驗證x1
q1 = np.dot(x1 , Wq)
k1 = np.dot(x1 , Wk)
v1 = np.dot(x1 , Wv)

print("q1 =", q1)
print("Q[0] =", Q[0])  # 應與 q1 相同

print("k1 =", k1)
print("K[0] =", K[0])  # 應與 k1 相同

print("v1 =", v1)
print("V[0] =", V[0])  # 應與 v1 相同

q1 = [2 0 4]
Q[0] = [2 0 4]
k1 = [1 5 3]
K[0] = [1 5 3]
v1 = [ 5  2 10]
V[0] = [ 5  2 10]


In [14]:
#驗證x2
q2 = np.dot(x2 , Wq)
k2 = np.dot(x2 , Wk)
v2 = np.dot(x2 , Wv)

print("q2 =", q2)
print("Q[1] =", Q[1])  # 應與 q2 相同

print("k2 =", k2)
print("K[1] =", K[1])  # 應與 k2 相同

print("v2 =", v2)
print("V[1] =", V[1])  # 應與 v2 相同

q2 = [ 1  0 -1]
Q[1] = [ 1  0 -1]
k2 = [0 0 1]
K[1] = [0 0 1]
v2 = [0 0 2]
V[1] = [0 0 2]


In [15]:
#驗證x2
q3 = np.dot(x3 , Wq)
k3 = np.dot(x3 , Wk)
v3 = np.dot(x3 , Wv)

print("q3 =", q3)
print("Q[2] =", Q[2])  # 應與 q3 相同

print("k3 =", k3)
print("K[2] =", K[2])  # 應與 k3 相同

print("v3 =", v3)
print("V[2] =", V[2])  # 應與 v3 相同

q3 = [0 0 0]
Q[2] = [0 0 0]
k3 = [-2  2 -2]
K[2] = [-2  2 -2]
v3 = [ 2 -4  0]
V[2] = [ 2 -4  0]
