<a href="https://colab.research.google.com/github/3B032049/2025_ML_hws/blob/main/hw6-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np


x1 = np.array([0.1, 0.2, 0.3])
x2 = np.array([0.5, 0.4, 0.3])
x3 = np.array([0.0, 0.1, 0.0])


Wx = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])  # shape: (3, 4)

Wh = np.array([
    [0.1, 0.0, 0.1, 0.0],
    [0.0, 0.1, 0.0, 0.1],
    [0.1, 0.1, 0.1, 0.1],
    [0.2, 0.2, 0.2, 0.2]
])  # shape: (4, 4)

b = np.array([0.01, 0.02, 0.03, 0.04])  # shape: (4,)

In [41]:
def tanh(x_t, h_prev):
    return np.tanh(np.dot(x_t, Wx) + np.dot(h_prev, Wh) + b)

In [42]:
# 初始狀態 h0 設為零向量
h0 = np.zeros(4)

# 時間步 t=1
h1 = tanh(x1, h0)
print("h1 =", h1)

# 時間步 t=2
h2 = tanh(x2, h1)
print("h2 =", h2)

# 時間步 t=3
h3 = tanh(x3, h2)
print("h3 =", h3)

h1 = [0.37136023 0.43008421 0.48538109 0.53704957]
h2 = [0.618816   0.69571962 0.75439786 0.80720563]
h3 = [0.34412356 0.36829826 0.37888962 0.40235267]


# hw6-3

In [43]:
# Decoder 第 3 步的 query 向量
S3 = np.array([2, 5, 3, 1])  # shape: (4,)

In [44]:
# 計算注意力強度 e1, e2, e3（內積）
e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)
e = np.array([e1, e2, e3])


In [45]:
print("注意力強度 e =", e)

注意力強度 e = [4.88633435 7.78662929 4.06875994]


In [46]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

a = softmax(e)  # [a1, a2, a3]
print("注意力權重 a =", a)

注意力權重 a = [0.05096578 0.92653276 0.02250146]


In [47]:
c3 = a[0] * h1 + a[1] * h2 + a[2] * h3
print("c3 =", c3)

c3 = [0.60002324 0.67481384 0.73223773 0.78432713]


# hw6-4

In [48]:
x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, -1])
x3 = np.array([-2, 0, 2])
X = np.stack([x1, x2, x3])  # shape: (3, 3)
# 整合為一個矩陣 X（3 個詞，維度為 3）


Wq = np.array([[0, 0 ,1],
        [1, 0 ,0],
        [0, 0 ,1]])

Wk = np.array([[1, 0 ,1],
        [0, 1 ,1],
        [0, 1 ,0]])

Wv = np.array([[0, 2 ,1],
        [1, 0 ,3],
        [1, 0 ,1]])

b = np.array([0.01, 0.02, 0.03, 0.04])  # shape: (4,)



In [49]:
#計算出Q,K,V及 根號dk
Q = X @ Wq
K = X @ Wk
V = X @ Wv

dk = K.shape[1]
sqrt_dk = np.sqrt(dk)

print("Q =\n", Q)
print("K =\n", K)
print("V =\n", V)
print("sqrt(dk) =", sqrt_dk)

Q =
 [[ 2  0  4]
 [ 1  0 -1]
 [ 0  0  0]]
K =
 [[ 1  5  3]
 [ 0  0  1]
 [-2  2 -2]]
V =
 [[ 5  2 10]
 [ 0  0  2]
 [ 2 -4  0]]
sqrt(dk) = 1.7320508075688772


In [50]:
def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / np.sum(e, axis=-1, keepdims=True)

In [51]:
scores = np.dot(Q, K.T) / np.sqrt(dk)
attention_weights = softmax(scores)
output = np.dot(attention_weights, V)

print("Attention weights =\n", attention_weights)
print("Self-Attention Output =\n", output)

Attention weights =
 [[9.96900485e-01 3.09921316e-03 3.01585787e-07]
 [1.67943450e-01 2.99159712e-01 5.32896838e-01]
 [3.33333333e-01 3.33333333e-01 3.33333333e-01]]
Self-Attention Output =
 [[ 4.98450303  1.99379976  9.97520328]
 [ 1.90551093 -1.79570045  2.27775393]
 [ 2.33333333 -0.66666667  4.        ]]


In [52]:
#驗證x1
q1 = np.dot(x1 , Wq)
k1 = np.dot(x1 , Wk)
v1 = np.dot(x1 , Wv)

print("q1 =", q1)
print("Q[0] =", Q[0])  # 應與 q1 相同

print("k1 =", k1)
print("K[0] =", K[0])  # 應與 k1 相同

print("v1 =", v1)
print("V[0] =", V[0])  # 應與 v1 相同

q1 = [2 0 4]
Q[0] = [2 0 4]
k1 = [1 5 3]
K[0] = [1 5 3]
v1 = [ 5  2 10]
V[0] = [ 5  2 10]


In [53]:
#驗證x2
q2 = np.dot(x2 , Wq)
k2 = np.dot(x2 , Wk)
v2 = np.dot(x2 , Wv)

print("q2 =", q2)
print("Q[1] =", Q[1])  # 應與 q2 相同

print("k2 =", k2)
print("K[1] =", K[1])  # 應與 k2 相同

print("v2 =", v2)
print("V[1] =", V[1])  # 應與 v2 相同

q2 = [ 1  0 -1]
Q[1] = [ 1  0 -1]
k2 = [0 0 1]
K[1] = [0 0 1]
v2 = [0 0 2]
V[1] = [0 0 2]


In [54]:
#驗證x2
q3 = np.dot(x3 , Wq)
k3 = np.dot(x3 , Wk)
v3 = np.dot(x3 , Wv)

print("q3 =", q3)
print("Q[2] =", Q[2])  # 應與 q3 相同

print("k3 =", k3)
print("K[2] =", K[2])  # 應與 k3 相同

print("v3 =", v3)
print("V[2] =", V[2])  # 應與 v3 相同

q3 = [0 0 0]
Q[2] = [0 0 0]
k3 = [-2  2 -2]
K[2] = [-2  2 -2]
v3 = [ 2 -4  0]
V[2] = [ 2 -4  0]
